In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
df_april2019 = pd.read_csv('./data/SpotifyAudioFeaturesApril2019.csv')
df_nov2018 = pd.read_csv('./data/SpotifyAudioFeaturesNov2018.csv')

In [21]:
df_april2019.head()

,artist_name,track_id,track_name,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,popularity
0,YG,2RM4jf1Xa9zPgMGRDiht8O,"Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj",0.005820,0.743,238373,0.339,0.000,1,0.0812,-7.678,1,0.4090,203.927,4,0.118,15
1,YG,1tHDG53xJNGsItRA3vfVgs,BAND DRUM (feat. A$AP Rocky),0.024400,0.846,214800,0.557,0.000,8,0.2860,-7.259,1,0.4570,159.009,4,0.371,0
2,R3HAB,6Wosx2euFPMT14UXiWudMy,Radio Silence,0.025000,0.603,138913,0.723,0.000,9,0.0824,-5.890,0,0.0454,114.966,4,0.382,56
3,Chris Cooq,3J2Jpw61sO7l6Hc7qdYV91,Lactose,0.029400,0.800,125381,0.579,0.912,5,0.0994,-12.118,0,0.0701,123.003,4,0.641,0
4,Chris Cooq,2jbYvQCyPgX3CdmAzeVeuS,Same - Original mix,0.000035,0.783,124016,0.792,0.878,7,0.0332,-10.277,1,0.0661,120.047,4,0.928,0

In [22]:
df_nov2018.head()

,artist_name,track_id,track_name,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,popularity
0,YG,2RM4jf1Xa9zPgMGRDiht8O,"Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj",0.005820,0.743,238373,0.339,0.000,1,0.0812,-7.678,1,0.4090,203.927,4,0.118,44
1,YG,1tHDG53xJNGsItRA3vfVgs,BAND DRUM (feat. A$AP Rocky),0.024400,0.846,214800,0.557,0.000,8,0.2860,-7.259,1,0.4570,159.009,4,0.371,10
2,R3HAB,6Wosx2euFPMT14UXiWudMy,Radio Silence,0.025000,0.603,138913,0.723,0.000,9,0.0824,-5.890,0,0.0454,114.966,4,0.382,63
3,Chris Cooq,3J2Jpw61sO7l6Hc7qdYV91,Lactose,0.029400,0.800,125381,0.579,0.912,5,0.0994,-12.118,0,0.0701,123.003,4,0.641,9
4,Chris Cooq,2jbYvQCyPgX3CdmAzeVeuS,Same - Original mix,0.000035,0.783,124016,0.792,0.878,7,0.0332,-10.277,1,0.0661,120.047,4,0.928,8

In [23]:
df_april2019.info()

<class 'pandas.DataFrame'>
RangeIndex: 130663 entries, 0 to 130662
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   artist_name       130663 non-null  str
 1   track_id          130663 non-null  str
 2   track_name        130662 non-null  str
 3   acousticness      130663 non-null  float64
 4   danceability      130663 non-null  float64
 5   duration_ms       130663 non-null  int64
 6   energy            130663 non-null  float64
 7   instrumentalness  130663 non-null  float64
 8   key               130663 non-null  int64
 9   liveness          130663 non-null  float64
 10  loudness          130663 non-null  float64
 11  mode              130663 non-null  int64
 12  speechiness       130663 non-null  float64
 13  tempo             130663 non-null  float64
 14  time_signature    130663 non-null  int64
 15  valence           130663 non-null  float64
 16  popularity        130663 non-null  int64
dtypes: float64(9), int64(5), str(3)
memory usage: 16.9 MB

In [24]:
df_nov2018.info()

<class 'pandas.DataFrame'>
RangeIndex: 116372 entries, 0 to 116371
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   artist_name       116372 non-null  str
 1   track_id          116372 non-null  str
 2   track_name        116371 non-null  str
 3   acousticness      116372 non-null  float64
 4   danceability      116372 non-null  float64
 5   duration_ms       116372 non-null  int64
 6   energy            116372 non-null  float64
 7   instrumentalness  116372 non-null  float64
 8   key               116372 non-null  int64
 9   liveness          116372 non-null  float64
 10  loudness          116372 non-null  float64
 11  mode              116372 non-null  int64
 12  speechiness       116372 non-null  float64
 13  tempo             116372 non-null  float64
 14  time_signature    116372 non-null  int64
 15  valence           116372 non-null  float64
 16  popularity        116372 non-null  int64
dtypes: float64(9), int64(5), str(3)
memory usage: 15.1 MB

In [25]:
df_april2019['popularity_2019'] = df_april2019['popularity']
df_april2019.drop(columns='popularity', inplace=True)

df_nov2018['popularity_2018'] = df_nov2018['popularity']
df_nov2018.drop(columns='popularity', inplace=True)

In [29]:
df_april2019['track_id'].dtype

In [30]:
df = df_nov2018.merge(df_april2019, on='track_id', how='outer', suffixes=['_2018', '_2019'])
df.head()

,artist_name_2018,track_id,track_name_2018,acousticness_2018,danceability_2018,duration_ms_2018,energy_2018,instrumentalness_2018,key_2018,liveness_2018,...,instrumentalness_2019,key_2019,liveness_2019,loudness_2019,mode_2019,speechiness_2019,tempo_2019,time_signature_2019,valence_2019,popularity_2019
0,PUSSYGANGCO,0009UBVA8DCDwk1Hepib6P,Kalifornia,0.0742,0.680,188813.0,0.395,0.050500,10.0,0.0958,...,0.050500,10.0,0.0958,-13.803,1.0,0.0438,124.018,4.0,0.0938,0.0
1,Jordan Sandhu,000RDCYioLteXcutOjeweY,Teeje Week,0.0583,0.679,190203.0,0.770,0.000000,0.0,0.0825,...,0.000000,0.0,0.0825,-3.537,1.0,0.1900,161.721,4.0,0.8390,52.0
2,NaN,000TqGTOAZjAIFU6SjmFmc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.306000,4.0,0.2190,-10.859,0.0,0.0743,137.949,4.0,0.0529,23.0
3,Panchito Arredondo,000v2QpqP2NmikGmSkLlCZ,Legado Del 20 (En Vivo),0.4260,0.850,134514.0,0.784,0.000011,5.0,0.1760,...,0.000011,5.0,0.1760,-6.794,1.0,0.1840,126.931,3.0,0.8440,21.0
4,Young Dolph,002QT7AS6h1LAF5dla8D92,Still Smell Like It,0.0469,0.830,207827.0,0.653,0.000000,1.0,0.1120,...,0.000000,1.0,0.1120,-5.298,1.0,0.1850,123.032,4.0,0.2280,49.0

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 131693 entries, 0 to 131692
Data columns (total 33 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   artist_name_2018       116836 non-null  str
 1   track_id               131693 non-null  str
 2   track_name_2018        116835 non-null  str
 3   acousticness_2018      116836 non-null  float64
 4   danceability_2018      116836 non-null  float64
 5   duration_ms_2018       116836 non-null  float64
 6   energy_2018            116836 non-null  float64
 7   instrumentalness_2018  116836 non-null  float64
 8   key_2018               116836 non-null  float64
 9   liveness_2018          116836 non-null  float64
 10  loudness_2018          116836 non-null  float64
 11  mode_2018              116836 non-null  float64
 12  speechiness_2018       116836 non-null  float64
 13  tempo_2018             116836 non-null  float64
 14  time_signature_2018    116836 non-null  float64
 15  valence_2018           116836 non-null  float64
 16  popularity_2018        116836 non-null  float64
 17  artist_name_2019       131030 non-null  str
 18  track_name_2019        131029 non-null  str
 19  acousticness_2019      131030 non-null  float64
 20  danceability_2019      131030 non-null  float64
 21  duration_ms_2019       131030 non-null  float64
 22  energy_2019            131030 non-null  float64
 23  instrumentalness_2019  131030 non-null  float64
 24  key_2019               131030 non-null  float64
 25  liveness_2019          131030 non-null  float64
 26  loudness_2019          131030 non-null  float64
 27  mode_2019              131030 non-null  float64
 28  speechiness_2019       131030 non-null  float64
 29  tempo_2019             131030 non-null  float64
 30  time_signature_2019    131030 non-null  float64
 31  valence_2019           131030 non-null  float64
 32  popularity_2019        131030 non-null  float64
dtypes: float64(28), str(5)
memory usage: 33.2 MB

In [35]:
df['popularity_difference'] = np.abs(df['popularity_2018'] - df['popularity_2019'])
df['popularity_difference']= df['popularity_difference'].fillna(0)
df['popularity_difference']

0         0.0
1         4.0
2         0.0
3         3.0
4         4.0
         ...
131688    0.0
131689    0.0
131690    1.0
131691    1.0
131692    0.0
Name: popularity_difference, Length: 131693, dtype: float64